<a href="https://colab.research.google.com/github/DianeUmurerwa/DIANE_INFO3020_SPRING2020/blob/master/Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#print a sting content

string =input("Please input a string: ")
print(string)

Please input a string: Hello World!
Hello World!


In [0]:
total = 0
for num in range (1,1001):
  if (num%2 == 0):
   total = total + num
print ("the total is ", total)

the total is  250500


In [61]:
#given a number list, write a function that gets the product of all the numbers in the list
def recursive_product(nested_number_list):
    product=1
    for element in nested_number_list:
        if type(element) is list:
            product*=i
    return product
numbers=[12,10,3,2,[6,[7,8,9],19,21],21]
print(recursive_product(numbers))


21


In [86]:
import numpy as np

matrix=[[23,43,12],[32,12,52],[15,35,52],[19,28,56]]

array = np.array(matrix)
print(np.where(array >20, 0, array))

[[ 0  0 12]
 [ 0 12  0]
 [15  0  0]
 [19  0  0]]
