<a href="https://colab.research.google.com/github/DianeUmurerwa/DIANE_INFO3020_SPRING2020/blob/master/FEB19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a= np.array([2,3,8])
print(2.1*a)
b=[2,3,8]
print(2*b)

print(np.dot(a,a))

[ 4.2  6.3 16.8]
[2, 3, 8, 2, 3, 8]
77


In [5]:
a=np.array([2,3,8])
a[2]
a[1:]

array([3, 8])

In [10]:
b = np.array([[2,3,8],[4,5,6]])
print(b[1,2])
print(b[:,1]) 
print(b[:][1])

6
[3 5]
[4 5 6]


In [12]:
#masking
a= np.array([230,10,284,39,76])
cutoff=200
print(a > cutoff)

[ True False  True False False]


In [13]:
import numpy as np

a= np.array([230,10,284,39,76])
cutoff = 200
new_a = []
for x in a:
  if x>cutoff:
    new_a.append(a)
  else:
     new_a.append(x)
a = np.array(new_a)
print(a)

[array([230,  10, 284,  39,  76]) 10 array([230,  10, 284,  39,  76]) 39
 76]


In [22]:
import numpy as np

a= np.array([[0,1],[2,3],[4,5]])
 
b= np.array([100,1000])
print(a*b)


[[   0 1000]
 [ 200 3000]
 [ 400 5000]]


In [0]:
with open("test.txt","w") as myfile:
  myfile.write("My first file written from python\n")
  myfile.write("---------------------------------\n")
  myfile.write("Hello, world!\n")